export const SubjectName = {
  arrays: 'Массивы',
  objects: 'Объекты',
  'hash-implementation': 'Реализация хеша',
  'prefix-sums': 'Префиксные суммы',
  stack: 'Стек',
  'two-pointers': 'Метод двух указателей',
  'sliding-window': 'Метод скользящего окна',
  'binary-search': 'Бинарный поиск',
  'linked-lists': 'Связные списки',
  'doubly-linked-lists': 'Двусвязные списки',
  queues: 'Очереди',
  'fast-and-slow-pointers': 'Быстрые и медленные указатели',
  'one-branch-recursion': 'Рекурсия (одна ветвь)',
  'two-branch-recursion': 'Рекурсия (две ветви)',
  'insertion-sort': 'Сортировка вставками',
  'merge-sort': 'Сортировка слиянием',
  'quick-sort': 'Быстрая сортировка',
  'bucket-sort': 'Блочная сортировка',
  'binary-tree': 'Бинарное дерево',
  'binary-search-tree': 'Бинарное дерево поиска',
  'bst-insert-and-remove': 'BST вставка и удаление',
  'depth-first-search': 'Поиск в глубину',
  'iterative-depth-first-search': 'Итеративный поиск в глубину',
  'breadth-first-search': 'Поиск в ширину',
  backtracking: 'Поиск с возвратом (бэктрекинг)',
  subsets: 'Подмножества',
  combinations: 'Сочетания',
  permutations: 'Перестановки',
  'intro-to-graphs': 'Введение в графы',
  'matrix-depth-first-search': 'Поиск в глубину в графе, представленным матрицей',
  'matrix-breadth-first-search': 'Поиск в ширину в графе, представленным матрицей',
  'adjacency-list': 'Список смежности',
  'heap-properties': 'Свойства кучи',
  'heap-push-and-pop': 'Куча: добавление и удаление',
  heapify: 'Преобразование массива в кучу (Heapify)'
};
