import type { TaskConfig } from 'types';
import {
  ARRAYS_AND_HASHING_TASKS,
  BACKTRACKING_TASKS,
  BINARY_SEARCH_TASKS,
  BIT_OPERATIONS_TASKS,
  GRAPHS_TASKS,
  GREEDY_TASKS,
  INTERVALS_TASKS,
  KADANES_ALGORITHM_TASKS,
  LINKED_LIST_TASKS,
  MATH_AND_GEOMETRY_TASKS,
  ONE_DIMENSION_DP_TASKS,
  RECURSION_TASKS,
  SLIDING_WINDOW_TASKS,
  SORTING_TASKS,
  STACK_TASKS,
  TREES_TASKS,
  TRIE_TASKS,
  TWO_POINTER_TASKS
} from './tasks-by-group';

export const TASKS: TaskConfig[] = ARRAYS_AND_HASHING_TASKS.concat(
  STACK_TASKS,
  TWO_POINTER_TASKS,
  SLIDING_WINDOW_TASKS,
  BINARY_SEARCH_TASKS,
  LINKED_LIST_TASKS,
  RECURSION_TASKS,
  SORTING_TASKS,
  TREES_TASKS,
  BACKTRACKING_TASKS,
  GRAPHS_TASKS,
  ONE_DIMENSION_DP_TASKS,
  INTERVALS_TASKS,
  TRIE_TASKS,
  KADANES_ALGORITHM_TASKS,
  GREEDY_TASKS,
  BIT_OPERATIONS_TASKS,
  MATH_AND_GEOMETRY_TASKS
);
